services:

  pingslurp:
    container_name: pingslurp
    image: brianoflondon/pingslurp:1.92
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    logging:
      driver: "json-file"
      options:
          max-file: "2"
          max-size: "2m"
    env_file:
      - ".env"
    # environment:
    #   DB_CONNECTION: "mongodb://mongodb-pp:27017"
    command: bash -c "poetry run pingslurper --verbose live"
    # command: ["--verbose", "live"]
    restart: unless-stopped
    networks:
      - pingslurp
      # - hive-network

volumes:
  mongodb-pingslurp-data:
    driver: local

networks:
  pingslurp:
  # hive-network:
  #   external: true


  # pingslurp-fillgaps:
  #   container_name: pingslurp-fillgaps
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   logging:
  #     driver: "json-file"
  #     options:
  #         max-file: "5"
  #         max-size: "10m"
  #   env_file:
  #     - ".env"
  #   # environment:
  #   #   DB_CONNECTION: "mongodb://mongodb-pp:27017"
  #   command: bash -c "python pingslurp.py fillgaps"
  #   restart: unless-stopped
  #   networks:
  #     - pingslurp
  #     - hive-network

  # mongodb:
  #   container_name: mongodb-pp
  #   hostname: mongodb-pp
  #   image: mongo:latest
  #   env_file:
  #     - ".env"
  #   ports:
  #     - "${LOCAL_TAILSCALE_IP}:27017:27017"
  #     - "127.0.1.1:27017:27017"
  #     - "127.0.0.1:27017:27017"
  #   # command: mongod --bind_ip localhost,${LOCAL_TAILSCALE_NAME} --replSet v4vapp-repl
  #   volumes:
  #     - mongodb-pingslurp-data:/data/db
  #   restart: always
  #   logging:
  #     driver: "json-file"
  #     options:
  #         max-file: "2"
  #         max-size: "2m"
  #   networks:
  #     - pingslurp
