version: '3'

services:

  mongodb:
    container_name: mongodb-pp
    hostname: mongodb-pp
    image: mongo:latest
    env_file:
      - ".env"
    ports:
      - "${LOCAL_TAILSCALE_IP}:27017:27017"
      - "127.0.1.1:27017:27017"
      - "127.0.0.1:27017:27017"
    # command: mongod --bind_ip localhost,${LOCAL_TAILSCALE_NAME} --replSet v4vapp-repl
    volumes:
      - mongodb-pp-data:/data/db
    restart: always
    logging:
      driver: "json-file"
      options:
          max-file: "5"
          max-size: "10m"
    networks:
      - podping-hive

  hive-podping:
    container_name: hive-podping
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ".env"
    environment:
      DB_CONNECTION: "mongodb://mongodb-pp:27017"
    command: bash -c "python scanner.py"
    restart: unless-stopped
    networks:
      - podping-hive

volumes:
  mongodb-pp-data:
    driver: local

networks:
  podping-hive:
