services:
  pingslurp:
    container_name: pingslurp
    image: brianoflondon/pingslurp:latest
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "2m"
    env_file:
      - ".env"
    # environment:
    #   DB_CONNECTION: "mongodb://mongodb-pp:27017"
    command: bash -c "poetry run pingslurper --verbose live"
    # command: ["--verbose", "live"]
    restart: unless-stopped
    dns:
      - 100.100.100.100
    networks:
      - repl-mongo_default

networks:
  repl-mongo_default:
    external: true
