[tool.poetry]
name = "podping-hive"
version = "0.1.0"
description = "Keeping up with the Podpings"
authors = ["Brian of London <brian@podping.org>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
lighthive = "^0.4.0"
pydantic = "^1.10.2"
black = "^22.10.0"
asgiref = "^3.5.2"
single-source = "^0.3.0"
motor = "^3.1.1"


[tool.poetry.group.dev.dependencies]
black = "^22.10.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
