[tool.poetry]
name = "podping-hive"
version = "0.1.0"
description = "Keeping up with the Podpings"
authors = ["Brian of London <brian@podping.org>"]
license = "MIT"
readme = "README.md"
packages = [{include = "podping_hive"}]

[tool.poetry.dependencies]
python = "^3.10"
lighthive = "^0.4.0"
pydantic = "^1.10.2"


[tool.poetry.group.dev.dependencies]
black = {version = "^22.10.0", allow-prereleases = true}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
